#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
############################################################################
#
# MODULE:	    ann.maskrcnn config
# PURPOSE:	    Configuration class used in ann.maskrcnn.* modules
# WRITTEN:  	2017    Ondrej Pesek
#                       Based on config.py by Waleed Abdulla (Matterport, Inc.)
#                           https://github.com/matterport/Mask_RCNN
# Licensed under the MIT License (see LICENSE for details)
#
#############################################################################


import math
import numpy as np


class ModelConfig(object):
    """
    Base configuration class.
    """

    # NOT RECOMMENDED TO MODIFY:

    # The strides of each layer of the FPN Pyramid. These values
    # are based on a Resnet101 backbone.
    BACKBONE_STRIDES = [4, 8, 16, 32, 64]

    ## RPN ##
    # Length of square anchor side in pixels
    RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)

    # Ratios of anchors at each cell (width/height)
    # A value of 1 represents a square anchor, and 0.5 is a wide anchor
    RPN_ANCHOR_RATIOS = [0.5, 1, 2]

    # Anchor stride
    # If 1 then anchors are created for each cell in the backbone feature map.
    # If 2, then anchors are created for every other cell, and so on.
    RPN_ANCHOR_STRIDE = 1  # 2 before change

    # Non-max suppression threshold to filter RPN proposals.
    # You can reduce this during training to generate more propsals.
    RPN_NMS_THRESHOLD = 0.7

    # How many anchors per image to use for RPN training
    RPN_TRAIN_ANCHORS_PER_IMAGE = 256

    # ROIs kept after non-maximum supression (training and inference)
    POST_NMS_ROIS_TRAINING = 2000
    POST_NMS_ROIS_INFERENCE = 1000

    # If True, pad images with zeros such that they're (max_dim by max_dim)
    IMAGE_PADDING = True  # currently, the False option is not supported

    # Image mean (RGB)
    MEAN_PIXEL = np.array([123.7, 116.8, 103.9])

    # Percent of positive ROIs used to train classifier/mask heads
    ROI_POSITIVE_RATIO = 0.33

    # Pooled ROIs
    POOL_SIZE = 7
    MASK_POOL_SIZE = 14
    MASK_SHAPE = [28, 28]

    # Maximum number of ground truth instances to use in one image
    MAX_GT_INSTANCES = 100

    # Bounding box refinement standard deviation for RPN and final detections.
    RPN_BBOX_STD_DEV = np.array([0.1, 0.1, 0.2, 0.2])
    BBOX_STD_DEV = np.array([0.1, 0.1, 0.2, 0.2])

    # Max number of final detections
    DETECTION_MAX_INSTANCES = 100

    # Minimum probability value to accept a detected instance
    # ROIs below this threshold are skipped
    DETECTION_MIN_CONFIDENCE = 0.7

    # Non-maximum suppression threshold for detection
    DETECTION_NMS_THRESHOLD = 0.3

    # Learning rate and momentum
    # The Mask RCNN paper uses lr=0.02, but on TensorFlow it causes
    # weights to explode. Likely due to differences in optimzer
    # implementation.
    LEARNING_RATE = 0.001  # 0.002 before change
    LEARNING_MOMENTUM = 0.9

    # Weight decay regularization
    WEIGHT_DECAY = 0.0001

    # Use RPN ROIs or externally generated ROIs for training
    # Keep this True for most situations. Set to False if you want to train
    # the head branches on ROI generated by code rather than the ROIs from
    # the RPN. For example, to debug the classifier head without having to
    # train the RPN.
    USE_RPN_ROIS = True

    def __init__(self, name='model', imagesPerGPU=1, GPUcount=1, numClasses=1,
                 trainROIsPerImage=64, stepsPerEpoch=1500,
                 miniMaskShape=None, validationSteps=100,
                 imageMaxDim=768, imageMinDim=768, backbone='resnet101'):
        """Set values of computed attributes."""

        # Give the configuration a recognizable name
        self.NAME = name

        # Number of images per GPU
        self.IMAGES_PER_GPU = imagesPerGPU

        # NUMBER OF GPUs to use. For CPU training, use 1
        self.GPU_COUNT = GPUcount

        # Number of classes (including background)
        self.NUM_CLASSES = numClasses
        self.TRAIN_ROIS_PER_IMAGE = trainROIsPerImage
        self.STEPS_PER_EPOCH = stepsPerEpoch // self.IMAGES_PER_GPU
        self.VALIDATION_STEPS = validationSteps
        self.IMAGE_MAX_DIM = imageMaxDim
        self.IMAGE_MIN_DIM = imageMinDim

        # mini_mask to save memory
        if miniMaskShape:
            self.USE_MINI_MASK = True
            self.MINI_MASK_SHAPE = tuple(int(a) for a in miniMaskShape.split(','))
        else:
            self.USE_MINI_MASK = False
            self.MINI_MASK_SHAPE = None

        # Effective batch size
        self.BATCH_SIZE = self.IMAGES_PER_GPU * self.GPU_COUNT

        # Input image size
        self.IMAGE_SHAPE = np.array(
            [self.IMAGE_MAX_DIM, self.IMAGE_MAX_DIM, 3])

        # Set the backbone architecture
        self.BACKBONE = backbone

        # Compute backbone size from input image size
        self.BACKBONE_SHAPES = np.array(
            [[int(math.ceil(self.IMAGE_SHAPE[0] / stride)),
              int(math.ceil(self.IMAGE_SHAPE[1] / stride))]
             for stride in self.BACKBONE_STRIDES])

    def display(self):
        """Display Configuration values."""
        print("\nConfigurations:")
        for a in dir(self):
            if not a.startswith("__") and not callable(getattr(self, a)):
                print("{:30} {}".format(a, getattr(self, a)))
        print("\n")
